const directions = {
 A: {name:'مساحة العمل',desc:'تنقّل واضح · توازن بين المتابعة والتنفيذ',detail:'شريط جانبي ثابت، بطاقات موجزة، وجداول مريحة. مناسب للعمل اليومي لمختلف الأدوار.'},
 B: {name:'استوديو الحملة',desc:'الحملة أولاً · مساحة أكبر للمحتوى',detail:'تنقّل أفقي، تكوين تحريري، ولوحات مرئية. مناسب لمراجعة المحتوى والعمل الإبداعي.'},
 C: {name:'مكتب العمليات',desc:'الأولوية للقرار · معلومات أكثر في مساحة أقل',detail:'شريط تنقّل مختصر، قوائم مقسّمة، ومعاينة بجانب العمل. مناسب لتنسيق الفريق والنشر.'}
};
const pages=[['home','الرئيسية','home'],['work','العمل','work'],['detail','تفاصيل العمل','file'],['create','إنشاء','plus'],['approvals','الموافقات والنشر','check'],['media','مكتبة الوسائط','image']];
const tasks=[['إعداد الفيديو الرئيسي','أحمد','قيد المراجعة','22 سبتمبر','video'],['تصميم الملصق','سارة','معتمد','21 سبتمبر','image'],['كتابة محتوى X','خالد','بحاجة إلى تعديل','20 سبتمبر','file'],['إعداد منشور Instagram','سارة','قيد المراجعة','22 سبتمبر','image'],['تغطية الحدث','عبدالله','مخطط','23 سبتمبر','video']];
const paths={home:'M3 10 12 3l9 7v10H3Z M9 20v-7h6v7',work:'M3 6h18v14H3Z M8 6V3h8v3 M3 11h18',file:'M6 3h8l4 4v14H6Z M14 3v5h4 M9 12h6 M9 16h6',plus:'M12 4v16 M4 12h16',check:'M4 12l5 5L20 6',image:'M3 3h18v18H3Z M3 17l5-5 5 5 3-3 5 5 M8 7h.01',video:'M3 5h13v14H3Z M16 10l5-3v10l-5-3',search:'M20 20l-5-5 M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',bell:'M5 17h14l-2-4V9a5 5 0 0 0-10 0v4Z M10 21h4',calendar:'M3 5h18v16H3Z M3 10h18 M7 2v6 M17 2v6',arrow:'M15 5l-7 7 7 7',grid:'M3 3h7v7H3Z M14 3h7v7h-7Z M3 14h7v7H3Z M14 14h7v7h-7Z',list:'M8 6h13 M8 12h13 M8 18h13 M3 6h.01 M3 12h.01 M3 18h.01',menu:'M3 6h18 M3 12h18 M3 18h18',clock:'M12 8v5l3 2 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',mail:'M3 5h18v14H3Z M3 5l9 8 9-8',settings:'M12 2v4 M12 18v4 M2 12h4 M18 12h4 M5 5l3 3 M16 16l3 3 M5 19l3-3 M16 8l3-3 M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',users:'M15 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0 M5 21v-3a7 7 0 0 1 14 0v3',chart:'M4 3v18h17 M8 16V9 M13 16V5 M18 16v-5'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.file}"/></svg>`}
const q=new URLSearchParams(location.search); let dir=q.get('direction')||'A', page=q.get('page')||'home'; if(!directions[dir])dir='A'; if(!pages.some(p=>p[0]===page))page='home';
const chip=(text)=>`<span class="chip ${text.includes('تعديل')||text.includes('انتباه')?'amber':text.includes('معتمد')||text.includes('جاهز')?'green':text.includes('مراجعة')?'purple':'neutral'}">${text}</span>`;
const button=(text,kind='',go='')=>`<button class="${kind}" ${go?`data-go="${go}"`:'data-notice'}>${text}</button>`;
const avatar=(name='محمد')=>`<span class="avatar">${name.slice(0,1)}</span>`;
const section=(title,body,link='')=>`<section class="panel"><div class="section-head"><h2>${title}</h2>${link?button('عرض الكل '+icon('arrow'),'text',link):''}</div>${body}</section>`;
function art(type='poster',small=false){return `<div class="art ${type} ${small?'small':''}"><div class="art-brand">الاتصال المؤسسي <span>٢٠٢٦</span></div><div class="art-lines"></div><div class="art-copy"><span>٢٣ سبتمبر · اليوم الوطني السعودي</span><strong>${type==='video'?'حكاية وطن':type==='raw'?'من الميدان':'وطنٌ نعتزّ به'}</strong><p>نحتفي بمنجزاتنا، ونصنع مستقبلنا معاً.</p></div><div class="art-base"><span>تصور إبداعي تجريبي</span><b>96</b></div>${type==='video'?'<span class="play">▷</span>':''}</div>`}
const stats=()=>`<div class="stats">${[['02','بانتظار موافقتك','check'],['05','أعمال الحملة','work'],['01','جاهز للنشر','calendar'],['01','يحتاج انتباه','bell']].map((s,i)=>`<div class="stat s${i}"><div>${icon(s[2])}<span>${s[1]}</span></div><strong>${s[0]}</strong><small>${i===0?'الفيديو ومنشور Instagram':i===3?'حساب LinkedIn':'اليوم الوطني السعودي 2026'}</small></div>`).join('')}</div>`;
function row(t,i=0){return `<button class="task-row" data-go="detail"><span class="item-icon">${icon(t[4])}</span><span class="task-name"><b>${t[0]}</b><small>اليوم الوطني السعودي 2026 · CH-${241+i}</small></span><span class="person">${avatar(t[1])}${t[1]}</span>${chip(t[2])}<span class="due">${t[3]}</span>${icon('arrow')}</button>`}
function campaign(){return `<section class="campaign"><div><span class="eyebrow">الحملة النشطة / سبتمبر 2026</span><h2>اليوم الوطني السعودي 2026</h2><p>قصة واحدة، يرويها فريقنا عبر كل القنوات.</p><div class="campaign-meta"><span>5 أعضاء</span><span>8 مواد إعلامية</span><span>23 سبتمبر</span></div>${button('استعراض أعمال الحملة '+icon('arrow'),'light','work')}</div><div class="progress-ring"><strong>72<span>%</span></strong><small>إنجاز الحملة</small></div></section>`}
function agenda(){return `<div class="agenda">${[['10:00','اجتماع تنسيق التغطية','الفريق الإعلامي'],['14:30','مراجعة الفيديو الرئيسي','محمد · أحمد'],['18:00','مراجعة خطة النشر','نورة · مسؤول النشر']].map(t=>`<div><time>${t[0]}</time><span><b>${t[1]}</b><small>${t[2]}</small></span><i></i></div>`).join('')}</div>`}
function attention(){return `<div class="attention">${icon('bell')}<div><b>قبل موعد النشر</b><p>حساب LinkedIn يحتاج إعادة ربط. بقية القنوات جاهزة.</p></div>${button('التفاصيل','text','approvals')}</div>`}
function home(){if(dir==='B')return `<div class="editorial-intro"><span class="eyebrow">الجمعة، 18 سبتمبر 2026</span><h1>صباح الخير، محمد.<br><em>حكاية الوطن تبدأ من هنا.</em></h1><p>خمسة أيام تفصلنا عن اليوم الوطني. إليك ما يحتاج قرارك اليوم.</p></div><div class="studio-home"><div class="hero-art">${art('poster')}${button('اليوم الوطني السعودي 2026 '+icon('arrow'),'art-link','work')}</div><div>${section('على مكتبك اليوم',`<div class="decision-number">02 <span>مواد بانتظار المراجعة</span></div>${row(tasks[0])}${row(tasks[3],3)}${button('الانتقال إلى المراجعة','primary wide','approvals')}`)}${attention()}</div></div><div class="columns">${section('إيقاع الحملة',`<div class="milestones"><div class="done">18 سبتمبر<b>الإنتاج والمراجعة</b></div><div>22 سبتمبر<b>الاعتماد النهائي</b></div><div>23 سبتمبر<b>النشر والتغطية</b></div></div>`)}${section('جدول اليوم',agenda())}</div>`;
 if(dir==='C')return `${heading('نظرة تشغيلية','الجمعة 18 سبتمبر 2026 · مدير الاتصال المؤسسي')}${stats()}<div class="operations"><div>${section('يتطلب قرارك الآن',`<div class="queue-label"><span>المادة / المسؤول</span><span>الموعد</span><span>الإجراء</span></div>${tasks.filter((_,i)=>i===0||i===3).map(t=>`<div class="decision-row"><div><b>${t[0]}</b><small>الإصدار ${t[1]==="أحمد"?4:2} · ${t[1]} · اليوم الوطني</small></div>${chip('قيد المراجعة')}${button('مراجعة','primary','approvals')}</div>`)}${attention()}`)}${section('متابعة التنفيذ',tasks.map(row).join(''),'work')}</div><aside>${section('الحملة الحالية',`<span class="eyebrow">ND · 2026</span><h2>اليوم الوطني السعودي</h2><div class="progress-bar"><i></i></div><div class="between"><b>72% مكتمل</b><small>5 أيام متبقية</small></div>`)}${section('جدول اليوم',agenda())}</aside></div>`;
 return `${heading('صباح الخير، محمد','الجمعة، 18 سبتمبر 2026 · ما يحتاج اهتمامك اليوم',button('إنشاء عمل '+icon('plus'),'primary','create'))}${stats()}<div class="columns wide-first"><div>${campaign()}${section('بانتظار موافقتك',row(tasks[0])+row(tasks[3],3),'approvals')}</div><div>${section('جدول اليوم',agenda())}${attention()}</div></div>${section('آخر نشاط للفريق',`<div class="activity-line">${avatar('سارة')}<p><b>سارة</b> أضافت النسخة النهائية من الملصق <small>قبل 35 دقيقة · اليوم الوطني السعودي 2026</small></p>${chip('الإصدار 5')}${button('عرض الوسائط','text','media')}</div>`)}`}
function heading(title,sub,action=''){return `<div class="page-heading"><div><span class="eyebrow">مركز الاتصال / ${pages.find(p=>p[0]===page)?.[1]||'العمل'}</span><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function tabs(labels){return `<div class="tabs">${labels.map((s,i)=>`<button class="${i===0?'active':''}" data-tab>${s}</button>`).join('')}</div>`}
function work(){let top=heading('العمل','كل ما نصنعه لليوم الوطني، في مكان واحد.',button('مهمة جديدة '+icon('plus'),'primary','create'))+tabs(['الكل  5','مهامي','الحملات','طلبات','متأخر','مكتمل']);let filters=`<div class="filters"><span class="field-like">${icon('search')} ابحث في العمل</span>${button('اليوم الوطني 2026 ⌄')}${button('الحالة ⌄')}${button('المسؤول ⌄')}<span class="spacer"></span>${button(icon('list'),'icon-button')}${button(icon('grid'),'icon-button')}</div>`;
 if(dir==='B')return top+`<div class="campaign-strip"><b>اليوم الوطني السعودي 2026</b><span>72% مكتمل</span><span>الإطلاق · 23 سبتمبر</span></div>`+filters+`<div class="board">${[['قيد التنفيذ',tasks.filter((_,i)=>i===2||i===4)],['قيد المراجعة',[tasks[0],tasks[3]]],['معتمد',[tasks[1]]]].map((col,i)=>`<section><h2><i class="dot d${i}"></i>${col[0]} <small>${col[1].length}</small></h2>${col[1].map((t,j)=>`<button class="board-card" data-go="detail">${i!==0?art(i===1?'video':'poster',true):''}<small>CH-${241+i+j} · اليوم الوطني</small><h3>${t[0]}</h3>${chip(t[2])}<div class="between"><span>${avatar(t[1])} ${t[1]}</span><span>${t[3]}</span></div></button>`).join('')}</section>`).join('')}</div>`;
 if(dir==='C')return top+filters+`<div class="split-work"><section class="panel compact-list">${tasks.map(row).join('')}</section><section class="panel inline-detail"><div class="between"><small>CH-241 / فيديو</small>${chip('قيد المراجعة')}</div><h2>إعداد الفيديو الرئيسي</h2>${art('video',true)}<p>فيلم قصير يروي قصة الانتماء ويبرز مشاركة الفريق في احتفالات اليوم الوطني.</p>${facts()}${button('فتح مساحة العمل '+icon('arrow'),'primary','detail')}</section></div>`;
 return top+filters+`<section class="panel work-table"><div class="table-header"><span>العنوان / الحملة</span><span>المسؤول</span><span>الحالة</span><span>الموعد</span></div>${tasks.map(row).join('')}<div class="table-footer">5 أعمال · جميعها مرتبطة بحملة اليوم الوطني السعودي 2026</div></section><div class="work-summary"><b>الفريق يعمل على قصة واحدة.</b><p>اربط المحتوى والوسائط بالمهمة لتبقى المراجعات في سياقها.</p>${button('عرض مكتبة الحملة '+icon('arrow'),'text','media')}</div>`}
function facts(){return `<dl class="facts"><div><dt>الحملة</dt><dd>اليوم الوطني السعودي 2026</dd></div><div><dt>المسؤول</dt><dd>${avatar('أحمد')} أحمد · المنتج الإعلامي</dd></div><div><dt>التسليم</dt><dd>22 سبتمبر 2026</dd></div><div><dt>الأولوية</dt><dd><span class="priority-dot"></span> عالية</dd></div></dl>`}
function checklist(){return `<div class="checklist">${[['✓','كتابة النص','خالد'],['✓','التصوير','أحمد'],['✓','المونتاج','أحمد'],['4','المراجعة النهائية','محمد']].map(t=>`<div><span class="step ${t[0]==='✓'?'done':''}">${t[0]}</span><b>${t[1]}</b><small>${t[2]}</small></div>`).join('')}</div>`}
function comments(){return `<div class="comment">${avatar('سارة')}<div><b>سارة <small>قبل 35 دقيقة</small></b><p>أضفت شاشة الختام بالهوية المعتمدة. النسخة الرابعة جاهزة للمراجعة.</p></div></div><label class="comment-input">إضافة تعليق<input placeholder="اكتب ملاحظتك للفريق…"></label>`}
function detail(){let title=heading('إعداد الفيديو الرئيسي','CH-241 · اليوم الوطني السعودي 2026',button('فتح المراجعة '+icon('arrow'),'primary','approvals'));let overview=`<div class="between">${chip('قيد المراجعة')}<small>الإصدار 4 · آخر تحديث منذ 18 دقيقة</small></div><p class="lead">فيلم قصير يحتفي باليوم الوطني، ويبرز قصص الانتماء والعطاء من داخل المؤسسة.</p>`;let main=section('معاينة العمل',overview+art('video')+`<div class="file-caption"><bdi>main-reel-v4.mp4</bdi><span>00:45 · 1080 × 1920</span>${button('الملفات','text','media')}</div>`);let side=section('تفاصيل العمل',facts())+section('مراحل الإنتاج',checklist());
 if(dir==='B')return title+tabs(['نظرة عامة','الملفات 4','التعليقات 3','النشاط','الموافقة'])+`<div class="studio-detail">${main}<div>${side}</div></div>`+section('حوار الفريق',comments());
 if(dir==='C')return title+`<div class="detail-three"><aside>${side}</aside><div>${tabs(['المحتوى','الملفات','الموافقة'])}${main}</div>${section('التعليقات والنشاط',comments()+`<div class="activity-note">أحمد أرسل الإصدار 4 للمراجعة<br><small>اليوم، 10:42 صباحاً</small></div>`)}</div>`;
 return title+tabs(['نظرة عامة','الملفات 4','التعليقات 3','النشاط','الموافقة'])+`<div class="columns wide-first"><div>${main}${section('التعليقات',comments())}</div><aside>${side}</aside></div>`}
function composer(){return `<label>عنوان المحتوى<input value="منشور اليوم الوطني السعودي"></label><label>الحملة<select><option>اليوم الوطني السعودي 2026</option></select></label>${tabs(['النص الأساسي','Instagram','X','LinkedIn'])}<label>نص المنشور<textarea rows="5">في يومنا الوطني، نحتفي بوطن يجمعنا على الطموح والعطاء. نفخر بمنجزاتنا، ونواصل العمل معاً لمستقبل يستحقه وطننا.\n\n#اليوم_الوطني_السعودي #وطن_نعتز_به</textarea></label><div class="between"><small>184 حرفاً</small>${button('اقتراح صياغة','text')}</div><label>قنوات النشر</label><div class="channels"><label><input type="checkbox" checked> Instagram</label><label><input type="checkbox" checked> X</label><label><input type="checkbox"> LinkedIn</label></div><div class="attachment">${icon('image')}<div><b>الملصق النهائي</b><small>الإصدار 5 · معتمد · 2.8 MB</small></div>${button('تغيير','text','media')}</div>`}
function preview(){return `<div class="social-preview"><div class="social-head">${avatar('مركز')}<div><b>مركز الاتصال المؤسسي</b><small>@organization · معاينة</small></div><span>•••</span></div>${art('poster')}<div class="social-copy"><b>في يومنا الوطني، نحتفي بوطن يجمعنا.</b><p>نفخر بمنجزاتنا، ونواصل العمل معاً لمستقبل يستحقه وطننا.</p><span>#اليوم_الوطني_السعودي</span></div></div>`}
function create(){let title=heading('مساحة الإنشاء','من الفكرة إلى محتوى جاهز للمراجعة.',button('حفظ مسودة','secondary')+button('إرسال للمراجعة','primary'));let types=`<div class="creation-types">${[['file','منشور اجتماعي'],['video','فيديو'],['image','تصميم'],['mail','بيان صحفي'],['calendar','تغطية حدث']].map((t,i)=>`<button class="${i===0?'active':''}" data-tab>${icon(t[0])}${t[1]}</button>`).join('')}</div>`;
 if(dir==='B')return title+`<div class="studio-compose"><aside>${types}<div class="helper"><b>رسالة الحملة</b><p>الانتماء والعطاء والطموح. لغة قريبة من الجمهور، بهوية مؤسسية واضحة.</p></div></aside><section class="panel">${composer()}</section><div><span class="eyebrow">معاينة مباشرة / Instagram</span>${preview()}</div></div>`;
 if(dir==='C')return title+`<div class="steps"><b>1 · المحتوى</b><span>2 · الوسائط والقنوات</span><span>3 · المراجعة</span></div><div class="compose">${section('بيانات المنشور',composer())}<aside>${section('ملخص الإصدار',`<dl class="facts"><div><dt>نوع المحتوى</dt><dd>منشور اجتماعي</dd></div><div><dt>المنشئ</dt><dd>خالد · كاتب المحتوى</dd></div><div><dt>حالة الإصدار</dt><dd>مسودة جديدة</dd></div></dl><p>تُراجع هذه النسخة قبل إتاحتها لمسؤول النشر.</p>`)}${preview()}</aside></div>`;
 return title+types+`<div class="compose">${section('تفاصيل المحتوى',composer())}<aside><div class="section-head"><h2>معاينة المنشور</h2>${chip('Instagram')}</div>${preview()}<p class="helper">المعاينة تقريبية. سيشمل طلب المراجعة النص والوسائط والقنوات المختارة.</p></aside></div>`}
function release(){return `<div class="release-header"><span class="eyebrow">أنت تراجع / الإصدار 4</span><h2>إعداد الفيديو الرئيسي</h2><p>أرسله أحمد · منذ 18 دقيقة</p></div>${art('video')}<p class="release-copy">في يومنا الوطني، نروي حكاية وطن نعتزّ به. قصص من العطاء والعمل، وطموح يتجدد كل يوم.</p><div class="release-meta"><span>الوسيط <bdi>main-reel-v4.mp4</bdi></span><span>القنوات <bdi>Instagram · X · LinkedIn</bdi></span><span>الموعد المقترح 23 سبتمبر · 18:00 الرياض</span></div><div class="review-actions">${button('اعتماد الإصدار 4 '+icon('check'),'primary')}${button('طلب تعديل','secondary')}${button('رفض','text danger')}</div>`}
function publishing(){return `<div class="publication"><div class="between"><h3>تصميم الملصق</h3>${chip('جاهز للنشر')}</div><p>الإصدار 5 · اعتمده محمد</p><div class="channel-state"><b>Instagram</b><span class="green-text">جاهز</span></div><div class="channel-state"><b>X</b><span class="green-text">جاهز</span></div><div class="channel-state"><b>LinkedIn</b><span class="amber-text">يحتاج إعادة ربط</span></div>${button('جدولة النشر '+icon('calendar'),'secondary wide')}</div>`}
function approvals(){let title=heading('الموافقات والنشر','قرارات واضحة، وإصدارات معتمدة قبل النشر.');let tab=tabs(['الموافقات  2','النشر  1']);let queue=`<div class="review-queue"><button class="selected" data-notice>${chip('قيد المراجعة')}<h3>إعداد الفيديو الرئيسي</h3><small>أحمد · الإصدار 4 · منذ 18 دقيقة</small></button><button data-notice><h3>إعداد منشور Instagram</h3><small>سارة · الإصدار 2 · منذ ساعة</small></button></div>`;
 if(dir==='B')return title+tab+`<div class="studio-review"><section class="panel release">${release()}</section><aside>${section('بانتظار القرار',queue)}${section('التالي في النشر',publishing())}</aside></div>`;
 return title+tab+`<div class="review-layout ${dir==='C'?'dense-review':''}"><aside>${section('يحتاج مراجعتي',queue)}${dir==='A'?section('جاهز للنشر',publishing()):''}</aside><section class="panel release">${release()}</section>${dir==='C'?`<aside>${section('حالة النشر',publishing())}${attention()}</aside>`:''}</div>`}
const assets=[['الملصق النهائي','poster-final.jpg','poster','معتمد','v5'],['الفيديو الرئيسي','main-reel-v4.mp4','video','قيد المراجعة','v4'],['ملف تصميم الملصق','poster-v3.psd','poster','نسخة سابقة','v3'],['لقطات التغطية','drone-shot.mov','raw','مواد أصلية','v1']];
function media(){let title=heading('مكتبة الوسائط','أصول الحملة، إصداراتها، وأماكن استخدامها.',button('إضافة ملف '+icon('plus'),'primary'));let tab=tabs(['الكل  4','صور','فيديو','تصاميم','مستندات','مؤرشف']);let filters=`<div class="filters"><span class="field-like">${icon('search')} ابحث بالاسم أو الوسم</span>${button('اليوم الوطني 2026 ⌄')}${button('حالة الاعتماد ⌄')}<span class="spacer"></span>${button(icon('grid'),'icon-button')}${button(icon('list'),'icon-button')}</div>`;
 if(dir==='C')return title+tab+filters+`<div class="media-inspector"><section class="panel"><div class="table-header"><span>الأصل / اسم الملف</span><span>الإصدار</span><span>الحالة</span></div>${assets.map(a=>`<button class="asset-row" data-notice><span class="mini-art">${art(a[2],true)}</span><span><b>${a[0]}</b><small dir="ltr">${a[1]}</small></span><span>${a[4]}</span>${chip(a[3])}</button>`).join('')}</section><aside class="panel">${art('poster')}<h2>الملصق النهائي</h2><dl class="facts"><div><dt>الإصدار الحالي / المعتمد</dt><dd>v5 / v5</dd></div><div><dt>أُنشئ بواسطة</dt><dd>سارة · المصمم</dd></div><div><dt>مستخدم في</dt><dd>منشور اليوم الوطني</dd></div></dl>${button('عرض الإصدارات','secondary wide')}</aside></div>`;
 return title+tab+filters+`<div class="media-grid ${dir==='B'?'editorial-grid':''}">${assets.map(a=>`<button class="media-card" data-notice>${art(a[2])}<div class="media-info"><div class="between"><h3>${a[0]}</h3><span>${a[4]}</span></div><small dir="ltr">${a[1]}</small><div class="between">${chip(a[3])}<small>${a[2]==='video'?'00:45 · 84 MB':'اليوم الوطني 2026'}</small></div></div></button>`).join('')}</div><div class="library-note">${icon('image')}<span>ملفات مترابطة، وإصدارات واضحة. اعتماد الملف مرتبط بنسخته المحددة.</span></div>`}
function nav(){return pages.filter(p=>p[0]!=='detail').map(p=>`<button class="nav-item ${page===p[0]?'active':''}" title="${p[1]}" data-go="${p[0]}">${icon(p[2])}<span>${p[1]}</span>${p[0]==='approvals'?'<b>2</b>':''}</button>`).join('')}
function render(){document.body.className='direction-'+dir;document.getElementById('review').innerHTML=`<div class="review-brand"><b>COMMS HUB</b><span>مراجعة التصميم · ليست النسخة التشغيلية</span></div><div class="direction-switch" dir="ltr">${Object.entries(directions).map(([k,v])=>`<button data-direction="${k}" class="${k===dir?'active':''}">${k}<span>${v.name}</span></button>`).join('')}</div><label class="screen-picker">الشاشة<select id="screen">${pages.map(p=>`<option value="${p[0]}" ${p[0]===page?'selected':''}>${p[1]}</option>`).join('')}</select></label><button id="mobile-toggle">${icon('menu')}<span>معاينة الجوال</span></button>`;
document.getElementById('app').innerHTML=`<div class="app-frame"><aside class="sidebar"><div class="brand"><span class="brandmark">${icon('chart')}</span><div><b>مركز الاتصال</b><small>COMMUNICATION HUB</small></div></div><span class="nav-caption">مساحة الفريق</span><nav>${nav()}${[['calendar','التقويم'],['mail','البريد'],['chart','التحليلات']].map(t=>`<button class="nav-item secondary-nav" data-notice title="${t[1]}">${icon(t[0])}<span>${t[1]}</span></button>`).join('')}</nav><div class="sidebar-bottom"><button class="nav-item" data-notice>${icon('settings')}<span>الإعدادات</span></button><div class="profile">${avatar()}<span><b>محمد</b><small>مدير الاتصال المؤسسي</small></span></div></div></aside><div class="workspace"><header class="topbar"><div class="top-brand"><b>مركز الاتصال</b></div><button class="search" data-notice>${icon('search')}<span>ابحث في مركز الاتصال…</span><kbd>Ctrl K</kbd></button><div class="top-actions"><span class="prototype">نموذج تجريبي</span><button class="role" data-notice>عرض بصفة: <b>مدير الاتصال المؤسسي</b> ⌄</button><button class="bell icon-button" aria-label="الإشعارات" data-notice>${icon('bell')}<i></i></button>${avatar()}</div></header>${dir==='B'?`<nav class="horizontal-nav">${nav()}</nav>`:''}<main>${({home,work,detail,create,approvals,media})[page]()}</main><footer class="direction-caption"><b>${dir} / ${directions[dir].name}</b><span>${directions[dir].desc}</span><small>بيانات محلية توضيحية · لا يوجد نشر فعلي</small></footer></div><nav class="mobile-nav">${nav()}<button data-more>${icon('menu')}<span>المزيد</span></button></nav></div>`;document.getElementById('screen').onchange=e=>navigate(e.target.value);document.getElementById('mobile-toggle').onclick=()=>{document.body.classList.toggle('phone-preview');document.getElementById('mobile-toggle').lastElementChild.textContent=document.body.classList.contains('phone-preview')?'معاينة سطح المكتب':'معاينة الجوال'};}
function navigate(next){page=next;history.replaceState(null,'',`?direction=${dir}&page=${page}`);render();window.scrollTo(0,0)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.direction){dir=b.dataset.direction;navigate(page)}else if(b.dataset.go)navigate(b.dataset.go);else if(b.hasAttribute('data-notice'))document.getElementById('notice').showModal();else if(b.hasAttribute('data-more')){document.querySelector('.sidebar').classList.toggle('mobile-open')}else if(b.hasAttribute('data-tab')){b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById('notice').showModal()}});render();

