'use client';
import Link from 'next/link';
import {useState} from 'react';
import {assets,campaign,roles,ready} from '@/lib/domain';
import {useHub} from '@/lib/store';
import {Title,Panel,Empty,MediaPreview,StatusChip} from './ui';
import {WorkList,WorkDetail,Composer,WorkRow} from './work';
import {Approvals,Calendar} from './operations';
import {Supporting} from './supporting';
function Home(){const {state}=useHub();const actor=roles[state.role];const focus=state.work.filter(w=>actor.review?w.status==='IN_REVIEW':actor.publish?ready(w):w.owner===state.role);const attention=state.work.filter(w=>['FAILED','PARTIAL','CHANGES_REQUESTED'].includes(w.status));return <><Title title={`صباح الخير، ${actor.user}`} sub={actor.priority}>{actor.create&&<Link href="/create" className="button primary">إنشاء عمل +</Link>}</Title><div className="stats">{[[focus.length,actor.review?'بانتظار قرارك':actor.publish?'إصدارات معتمدة':'أعمالك'],[state.work.length,'أعمال الحملة'],[state.work.filter(w=>w.status==='SCHEDULED').length,'مجدول للنشر'],[attention.length,'يحتاج متابعة']].map(([n,t])=><div className="stat" key={t}><span>{t}</span><strong>{n}</strong><small>{campaign.title}</small></div>)}</div>{actor.admin?<Panel title="إدارة النظام"><p>إعدادات المستخدمين والتكاملات محاكاة فقط. لا يملك Admin صلاحية اعتماد المحتوى.</p><Link href="/admin" className="button primary">فتح الإدارة</Link></Panel>:null}<div className="columns wide-first"><div><section className="campaign"><span className="eyebrow">الحملة النشطة · سبتمبر 2026</span><h2>{campaign.title}</h2><p>{campaign.description}</p><div className="actions"><span>{state.work.length} أعمال</span><span>23 سبتمبر</span><Link href="/work" className="button light">استعراض أعمال الحملة ←</Link></div></section><Panel title={actor.review?'بانتظار موافقتك':actor.publish?'جاهزيتك للنشر':'أولويات العمل'}>{focus.length?focus.map(w=><WorkRow work={w} key={w.id}/>):<Empty>لا يوجد عمل يتطلب هذا الدور حالياً.</Empty>}</Panel></div><aside><Panel title="جدول الحملة">{state.work.filter(w=>w.scheduled).map(w=><Link key={w.id} className="notice" href="/calendar"><b>{w.title}</b><small>{w.scheduled?.replace('T',' · ')} الرياض</small></Link>)}<Link className="notice" href="/calendar"><b>23 سبتمبر · تغطية الحدث</b><small>عبدالله والفريق الإعلامي</small></Link></Panel><Panel title="يحتاج متابعة">{attention.map(w=><Link href={`/work/${w.id}`} className="notice" key={w.id}><b>{w.title}</b><StatusChip status={w.status}/></Link>)}{!attention.length&&<p>لا توجد عوائق في العمل الحالي.</p>}</Panel></aside></div><Panel title="نشاط الفريق">{state.work.flatMap(w=>w.activity.slice(0,1).map(a=><Link key={w.id} href={`/work/${w.id}`} className="notice"><b>{w.title}</b><p>{a}</p></Link>)).slice(0,4)}</Panel></>}
function Media({id}:{id?:string}){const {state}=useHub();const [search,setSearch]=useState('');const [kind,setKind]=useState('all');const [list,setList]=useState(false);const [version,setVersion]=useState<number|null>(null);const asset=assets.find(a=>a.id===id);if(id&&!asset)return <Empty>الوسيط غير موجود.</Empty>;if(asset)return <><Title title={asset.title} sub={campaign.title}><Link href="/media" className="button">العودة للمكتبة</Link></Title><div className="columns wide-first"><Panel><MediaPreview assetId={asset.id} version={version||asset.versions.at(-1)} large/><label>استعراض الإصدارات<select value={version||asset.versions.at(-1)} onChange={e=>setVersion(Number(e.target.value))}>{asset.versions.map(v=><option value={v} key={v}>v{v}{asset.approved===v?' · معتمد':''}</option>)}</select></label><p>{asset.filename} · أُنشئ بواسطة {asset.creator}</p><small>نسخة مرئية تجريبية. الملفات الثنائية والتخزين غير متصلين.</small></Panel><Panel title="مستخدم في">{state.work.filter(w=>w.assetId===asset.id).map(w=><Link href={`/work/${w.id}`} className="notice" key={w.id}><b>{w.title}</b><small>الوسيط v{w.assetVersion} · العمل r{w.revision}</small></Link>)}</Panel></div></>;const filtered=assets.filter(a=>(kind==='all'||a.kind===kind)&&(a.title+' '+a.filename).includes(search));return <><Title title="مكتبة الوسائط" sub="أصول الحملة وإصداراتها، مرتبطة بالعمل والمراجعة."/><div className="filters"><input aria-label="البحث في الوسائط" value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث عن وسيط…"/><select aria-label="نوع الوسائط" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">كل الوسائط</option><option value="poster">تصاميم</option><option value="video">فيديو</option><option value="raw">مواد أصلية</option></select><button onClick={()=>setList(!list)}>{list?'عرض الشبكة':'عرض القائمة'}</button></div><div className={list?'asset-list':'media-grid'}>{filtered.map(a=><Link className="media-card" href={`/media/${a.id}`} key={a.id}><MediaPreview assetId={a.id} version={a.versions.at(-1)}/><div><h2>{a.title}</h2><p>{campaign.title}</p><small>{a.filename} · v{a.versions.at(-1)}</small><span className="chip">{a.approved?'معتمد v'+a.approved:'غير معتمد'}</span></div></Link>)}</div>{!filtered.length&&<Empty>لا توجد وسائط مطابقة.</Empty>}</>}
export function HubPage({route}:{route:string[]}){const {state}=useHub();const [page,id,action]=route;if(!page)return <Home/>;if(page==='work'){if(!id)return <WorkList/>;if(action==='edit'){const w=state.work.find(w=>w.id===id);return w?<Composer key={w.id} work={w}/>:<Empty>العمل غير موجود.</Empty>}return <WorkDetail key={id} id={id}/>};if(page==='create')return <Composer key={'new-'+state.role}/>;if(page==='approvals')return <Approvals key={state.role}/>;if(page==='calendar')return <Calendar/>;if(page==='media')return <Media key={id||'all'} id={id}/>;if(['mail','ideas','analytics','monitoring','admin','settings','account'].includes(page))return <Supporting page={page}/>;return <Empty>هذه الصفحة غير موجودة. <Link href="/">العودة للرئيسية</Link></Empty>}
