const fs=require('node:fs'),path=require('node:path');
const {chromium}=require('C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));global.page=page;const out=path.join(__dirname,'artifacts');fs.mkdirSync(out,{recursive:true});
const role=async r=>page.getByLabel('عرض بصفة',{exact:true}).selectOption(r);const nav=async p=>{await page.locator(`.sidebar a[href="${p}"]`).click();await page.waitForURL("**"+p);await page.locator("main h1").filter({hasText:({"/work":"العمل","/create":"مساحة الإنشاء","/approvals":"الموافقات والنشر","/calendar":"التقويم"})[p]}).waitFor()};
await page.goto('http://127.0.0.1:3000');await role('writer');await nav('/create');await page.getByLabel('عنوان العمل',{exact:true}).fill('رسالة الوطن للتحقق');await page.locator('main textarea').first().fill('نحتفي بالوطن ونشكر فريقنا على العطاء');await page.getByRole('button',{name:'إرسال للمراجعة',exact:true}).click();await page.getByRole('link').filter({hasText:'رسالة الوطن للتحقق'}).first().click();const detailURL=page.url();
await role('director');await nav('/approvals');await page.getByRole('button').filter({hasText:'رسالة الوطن للتحقق'}).click();await page.getByRole('button',{name:'طلب تعديل',exact:true}).click();await page.getByLabel('الملاحظات',{exact:true}).fill('أضف شكر المتطوعين');await page.getByRole('button',{name:'تأكيد',exact:true}).click();
await role('writer');await nav('/work');await page.getByRole('link').filter({hasText:'رسالة الوطن للتحقق'}).first().click();await page.getByRole('link',{name:'تحرير',exact:true}).click();await page.locator('main textarea').first().fill('نحتفي بالوطن ونشكر فريقنا والمتطوعين');await page.getByRole('button',{name:'حفظ إصدار جديد',exact:true}).click();await page.getByRole('button',{name:/إرسال الإصدار 2 للمراجعة/}).click();
await role('assistant');await nav('/approvals');await page.getByRole('button').filter({hasText:'رسالة الوطن للتحقق'}).click();await page.getByRole('button',{name:'اعتماد الإصدار 2',exact:true}).click();await role('publisher');await page.getByRole('button').filter({hasText:'رسالة الوطن للتحقق'}).click();await page.getByRole('button',{name:'جدولة',exact:true}).click();await page.getByLabel('الموعد بتوقيت الرياض').fill('2026-09-23T18:00');await page.getByRole('button',{name:'تأكيد',exact:true}).click();await nav('/calendar');await page.getByRole('button').filter({hasText:'رسالة الوطن للتحقق'}).first().waitFor();await nav('/approvals');await page.getByRole('button').filter({hasText:'رسالة الوطن للتحقق'}).click();await page.getByRole('button',{name:'محاكاة النشر',exact:true}).click();await page.getByLabel('نتيجة المحاكاة').selectOption('partial');await page.getByRole('button',{name:'تأكيد المحاكاة',exact:true}).click();await page.getByRole('button',{name:'إعادة محاولة القنوات الفاشلة'}).waitFor();await page.screenshot({path:path.join(out,'partial-publication.png'),fullPage:true});await page.getByRole('button',{name:'إعادة محاولة القنوات الفاشلة'}).click();await page.locator('.channel-results').getByText('تم النشر',{exact:true}).first().waitFor();await page.waitForFunction(()=>document.querySelectorAll('.channel-results .success').length===2);await role('admin');if(await page.getByRole('button',{name:'محاكاة النشر',exact:true}).count())errors.push('Admin publish action exposed');
const views=[];for(const width of [1440,1280,900,390]){await page.setViewportSize({width,height:900});for(const route of ['/','/work','/work/CH-241','/create','/approvals','/calendar','/media','/media/poster','/mail','/ideas','/analytics','/monitoring','/settings','/account','/admin']){await page.goto('http://127.0.0.1:3000'+route);await page.locator('main').waitFor();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);views.push({width,route,overflow});if(width===1440&&route==='/')await page.screenshot({path:path.join(out,'home-desktop.png'),fullPage:true});if(width===390&&['/','/work','/create','/approvals'].includes(route))await page.screenshot({path:path.join(out,route==='/'?'home-mobile.png':route.slice(1)+'-mobile.png'),fullPage:true});}}
await page.goto('http://127.0.0.1:3000');await page.getByRole('button',{name:'المزيد',exact:true}).click();await page.locator('.sidebar.mobile-open').waitFor();await page.getByRole('button',{name:'الإشعارات',exact:true}).click();await page.keyboard.press('Escape');if(await page.locator('dialog[open]').count())errors.push('Escape failed');
const report={journey:'PASS: create > revision request > edit > resubmit > approve > schedule > calendar > partial publish > retry; Admin separation',views,errors,failed:views.filter(v=>v.overflow)};fs.writeFileSync(path.join(__dirname,'verification.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({journey:report.journey,views:views.length,errors,failed:report.failed}));await browser.close();if(errors.length||report.failed.length)process.exit(1);
})().catch(async e=>{console.error(e);console.log('FINAL',global.page?.url(),await global.page?.locator('main').innerText());await global.page?.screenshot({path:'qa/artifacts/failure.png'});process.exit(1)});




